import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { captureExplicitFacts, loadVisitorForChat, processVisitorRequest, upgradeVisitor, VisitorError } from "./visitor";
import { buildMessages } from "./concierge";
const env=(dir:string):NodeJS.ProcessEnv=>({NODE_ENV:"test",HERMES_CONCIERGE_STATE_DIR:dir,HERMES_CONCIERGE_SALT:"synthetic-visitor-salt-long-enough",HERMES_CONCIERGE_PROXY_KEY:"synthetic-proxy-key-long-enough",HERMES_CONCIERGE_ORIGIN:"https://portfolio.test"});
async function openSession(e:NodeJS.ProcessEnv){const r=await processVisitorRequest(new Request("https://portfolio.test/api/concierge/visitor",{method:"POST",headers:{origin:"https://portfolio.test","content-type":"application/json","x-concierge-proxy":e.HERMES_CONCIERGE_PROXY_KEY!,"x-real-ip":"192.0.2.1"},body:'{"action":"bootstrap"}'}),e);return {cookie:r.setCookie!.split(";")[0],snapshot:r.snapshot};}
function request(e:NodeJS.ProcessEnv,cookie:string,csrf:string){return new Request("https://portfolio.test",{headers:{origin:"https://portfolio.test","x-concierge-proxy":e.HERMES_CONCIERGE_PROXY_KEY!,cookie,"x-nora-csrf":csrf}});}
function action(e:NodeJS.ProcessEnv,cookie:string,csrf:string,a:unknown){const r=request(e,cookie,csrf);return processVisitorRequest(new Request(r.url,{method:"POST",headers:{...Object.fromEntries(r.headers),"content-type":"application/json"},body:JSON.stringify(a)}),e);}
test("opaque stable bootstrap, opt-in default project, and forget-all preserve quota",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"visitor-test-"));try{const e=env(dir),a=await openSession(e);assert.equal(a.snapshot.quota.limit,300);assert.equal(JSON.stringify(await readFile(path.join(dir,"visitor-state.json"),"utf8")).includes(a.cookie.split("=")[1]),false);const x=await action(e,a.cookie,a.snapshot.csrfToken,{action:"consent",enabled:true});assert.ok(x.snapshot.memory.activeProjectId);assert.equal(x.snapshot.memory.projects.length,1);const y=await action(e,a.cookie,x.snapshot.csrfToken,{action:"forgetAll"});assert.equal(y.snapshot.memory.enabled,false);assert.equal(y.snapshot.quota.limit,300);}finally{await rm(dir,{recursive:true,force:true});}});
test("CSRF, 30/150 per-session boundaries, and lead receipt ownership binding",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"visitor-quota-"));try{const e=env(dir),a=await openSession(e),b=await openSession(e);await assert.rejects(action(e,a.cookie,"wrong",{action:"consent",enabled:true}),VisitorError);const id="11111111-1111-4111-8111-111111111111",lead="22222222-2222-4222-8222-222222222222";await upgradeVisitor(request(e,a.cookie,a.snapshot.csrfToken),lead,id,e);await upgradeVisitor(request(e,a.cookie,a.snapshot.csrfToken),lead,id,e);await assert.rejects(upgradeVisitor(request(e,b.cookie,b.snapshot.csrfToken),lead,id,e),(x:unknown)=>x instanceof VisitorError&&x.code==="registration_owner_conflict");for(let i=0;i<300;i++)await loadVisitorForChat(request(e,a.cookie,a.snapshot.csrfToken),e);assert.equal((await processVisitorRequest(new Request("https://portfolio.test/api/concierge/visitor",{method:"POST",headers:{origin:"https://portfolio.test","content-type":"application/json","x-concierge-proxy":e.HERMES_CONCIERGE_PROXY_KEY!,cookie:a.cookie,"x-nora-csrf":a.snapshot.csrfToken},body:'{"action":"bootstrap"}'}),e)).snapshot.quota.limit,300);await assert.rejects(loadVisitorForChat(request(e,a.cookie,a.snapshot.csrfToken),e),(x:unknown)=>x instanceof VisitorError&&x.status===429);}finally{await rm(dir,{recursive:true,force:true});}});
test("explicit facts filter sensitive data, replace corrections, and generation-fence late completions",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"visitor-memory-"));try{const e=env(dir),a=await openSession(e),enabled=await action(e,a.cookie,a.snapshot.csrfToken,{action:"consent",enabled:true}),project=enabled.snapshot.memory.activeProjectId!;await captureExplicitFacts(request(e,a.cookie,enabled.snapshot.csrfToken),e,project,"My name is Alice. I want to improve retail conversion.",1);const after=await action(e,a.cookie,enabled.snapshot.csrfToken,{action:"bootstrap"});const version=JSON.parse(await readFile(path.join(dir,"visitor-state.json"),"utf8")).sessions[Object.keys(JSON.parse(await readFile(path.join(dir,"visitor-state.json"),"utf8")).sessions)[0]].version;await captureExplicitFacts(request(e,a.cookie,enabled.snapshot.csrfToken),e,project,"My name is Alicia. My password is secret.",version);const projectData=after.snapshot.memory.projects[0],prompt=buildMessages("en",[{role:"user",content:"help"}],projectData)[1].content;assert.match(prompt,/Alice/);assert.doesNotMatch(prompt,/secret/);const pending=await loadVisitorForChat(request(e,a.cookie,enabled.snapshot.csrfToken),e);await action(e,a.cookie,enabled.snapshot.csrfToken,{action:"forgetAll"});await captureExplicitFacts(request(e,a.cookie,enabled.snapshot.csrfToken),e,project,"My name is Late.",pending.version);const state=JSON.parse(await readFile(path.join(dir,"visitor-state.json"),"utf8"));assert.equal(state.sessions[Object.keys(state.sessions)[0]].memory.projects.length,0);}finally{await rm(dir,{recursive:true,force:true});}});
